#################################################################
# Copy the supervisor.conf.j2template in /etc/supervisor/conf.d
# for each supervisord_programs configured.
#################################################################
- name: Setup supervisor config
  template: src=supervisor.conf.j2 dest={{ supervisord_config_location }}/{{ item.value['program_name'] }}.conf
  with_dict: "{{ supervisord_programs }}"
